version: '3'

services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /dev/bus/usb:/dev/bus/usb
    command: sleep infinity
    privileged: true
