version: '3.3'
services:
  db:
    image: "postgres:${POSTGRESQL_VERSION}"
    container_name: "postgres${POSTGRESQL_VERSION}"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRESQL_USER}"
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
    volumes:
      # Where our data will be persisted
      - db:/var/lib/postgresql/data
volumes:
  db: