version: '3.3'
services:
  rabbitmq:
    image: "docker.io/bitnami/rabbitmq:${RABBITMQ_VERSION}"
    container_name: "rabbitmq${RABBITMQ_VERSION}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      # Where our data will be persisted
      - data:/bitnami/rabbitmq/mnesia
volumes:
  data:
    driver: local